### PR TITLE
updating OGH with OXL

### PR DESCRIPTION
**Pull request by jphuong**
OXL is now a subclass of OGH, and a usecase8 has been incorporated for complex netcdf libraries.

### CODE REVIEW

**Comment by jphuong** [comment]
These pull requests are failing because version 0.1.10 doesn't exist. At the start of these pull requests, the library was at ogh-0.1.11, so it seems to be recognizing the wrong recent version.

@lsetiawan @ocefpaf Is it possible to get TravisCI, setup.py and/or versioneer.py to recognize ogh-0.1.11 as the recent stable version?

**Comment by ocefpaf** [comment]
@jphuong `versioneer` will compute the version based on the `tag` and, for unreleased versions, base on the git commit. If you are stable `0.1.11` you have to tag it, but I don't think that is the problem here. Looking at the logs I see that the source tarball is getting named `ogh-.0.1.10+22.g3bba502.tar.gz`, so something is amiss right after the `-`.

**Comment by jphuong** [comment]
@ocefpaf @lsetiawan You are right. Fixing the release tag name seems to have resolved the build version problem. It's finding the ogh-0.1.10 tarball now and progressing into the unit tests. 

It's not using 0.1.11 as the latest release. This is likely because I just revised the release tag for 0.1.10. There is still a backlog of pull requests to be resolved before the 0.1.12 or 0.2.0 release. 

Would it be advised to trash any of these pull requests?

**Comment by lsetiawan** [comment]
Are you planning to merge these? @jphuong

**Comment by jphuong** [comment]
@lsetiawan I've just made my final checks. The build should take about 15 minutes. Could you please merge these?

**Pull request merged**
